FROM python:3.10

ENV TZ="Asia/Shanghai"

# RUN apt update && apt -y upgrade

# ubuntu
RUN useradd -m -u 1000 -s /bin/bash hello
# alpine
# RUN adduser -D -u 1000 hello
USER hello
ENV PATH="/home/hello/.local/bin:$PATH"

ADD ./deployments/pip.txt  ./

RUN pip3 config set global.index-url 'https://pypi.douban.com/simple/' && \
  pip3 config set install.trusted-host 'pypi.douban/simple' &&  \
  pip3 install --no-cache -r pip.txt
