project: chatgpt-proxy
repository: https://github.com/d2jvkpn/chatgpt-proxy
version: 0.1.0

config: |
  # path: configs/{{.APP_ENV}}.yaml
  allow_ips:
    enable: true
    items: [127.0.0.1]
  allow_api_keys:
    enable: false
    items: []
  tls:
    enable: false
    crt: configs/server.crt
    key: configs/server.key
  #
  chatgpt:
    api_key: sk-xxxxx
    proxy: socks5://localhost:1081
  #
  chatgpt_example2:
    # with suffix /v1 for github.com/sashabaranov/go-openai
    url: http://127.0.0.1:8080/v1
  chatgpt_example3:
    # with suffix /v1 for github.com/sashabaranov/go-openai
    url: https://127.0.0.1:8080/v1
    tls_skip_verify: true
